name: 更新网站
on: 
  workflow_dispatch:
    inputs:
      actUpdated:
        description: '更新了吗(yes/no)'     
        required: true
        default: 'yes'
      actVersion:
        description: '游戏版本号(x.xx)'     
        required: true
        default: '5.31'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Build
        run: bash make.sh
        env:
          ACT_UPDATED: ${{ github.event.inputs.actUpdated }}
          ACT_VERSION: ${{ github.event.inputs.actVersion }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: www
          CLEAN: true
